---
version: '3'

includes:
  lint: .config/linter/Taskfile.yml
  npm: .config/npm/Taskfile.yml
  workadventure: .config/workadventure/Taskfile.yml

tasks:
  code:
    cmds:
      - task: lint:megalinter

  build:
    cmds:
      - task: npm:install
      - task: npm:build

  deploy:
    cmds:
      - task: build
      - task: workadventure:setup_api_key
      - task: workadventure:setup_map_storage
      - task: workadventure:create_env_file
      - task: workadventure:upload_mode
