---
version: '3'

megalinter:
  desc: MegaLinter is an Open-Source tool for CI/CD workflows
  cmds:
    - docker run --rm -v /var/run/docker.sock:/var/run/docker.sock:rw -v $(pwd):/tmp/lint:rw oxsecurity/megalinter:v7
