---
name: "Code"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Set TERM environment variable
        run: echo "TERM=xterm" >> $GITHUB_ENV
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      
      - name: Install Task
        uses: arduino/setup-task@v2
      
      - name: Check install
        run: task -a
      
      - name: Run Megalinter
        run: task code

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: MegaLinter reports
          path: |
            megalinter-reports
            mega-linter.log

  build:
    runs-on: ubuntu-latest
    needs: code
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"
      
      - name: Install Task
        uses: arduino/setup-task@v2

      - name: "Install dependencies"
        run: task build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install Task
        uses: arduino/setup-task@v2
      
      - name: "Setup deploy"
        env:
          API_KEY: ${{ secrets.API_KEY }}
          URL_MAP_STORAGE: ${{ secrets.URL_MAP_STORAGE }}
        run: task deploy

      - name: Deploy in MAP STORAGE
        if: ${{ env.UPLOAD_MODE == 'MAP_STORAGE' }}
        run: task workadventure:deploy_map_storage

      - name: Deploy on GITHUB PAGES
        if: ${{ env.UPLOAD_MODE == 'GH_PAGES' }}
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist/
          BASE_BRANCH: master
