# MegaLinter GitHub Action configuration file
# More info at https://megalinter.io
---
name: MegaLinter
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  megalinter:
    name: MegaLinter
    runs-on: ubuntu-latest

    steps:
      # Git Checkout
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: MegaLinter
        uses: oxsecurity/megalinter/flavors/javascript@v7.9.0
        id: ml
